/**
 * Stable error codes for API responses
 * Used to provide consistent error handling on the client side
 */

export const ErrorCode = {
  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Authentication
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  // Resources
  ENTITY_NOT_FOUND: "ENTITY_NOT_FOUND",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  VARIANT_NOT_FOUND: "VARIANT_NOT_FOUND",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ADDRESS_NOT_FOUND: "ADDRESS_NOT_FOUND",

  // Conflicts
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
  DUPLICATE_SKU: "DUPLICATE_SKU",
  DUPLICATE_SLUG: "DUPLICATE_SLUG",
  DUPLICATE_PROMOTION_CODE: "DUPLICATE_PROMOTION_CODE",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  DUPLICATE_REQUEST: "DUPLICATE_REQUEST",

  // Business rules
  OUT_OF_STOCK: "OUT_OF_STOCK",
  INVALID_STOCK_ADJUSTMENT: "INVALID_STOCK_ADJUSTMENT",
  CART_EMPTY: "CART_EMPTY",
  CHECKOUT_EXPIRED: "CHECKOUT_EXPIRED",
  CHECKOUT_NOT_ALLOWED: "CHECKOUT_NOT_ALLOWED",

  // Promotions
  PROMOTION_INVALID: "PROMOTION_INVALID",
  PROMOTION_EXPIRED: "PROMOTION_EXPIRED",
  PROMOTION_LIMIT_REACHED: "PROMOTION_LIMIT_REACHED",
  PROMOTION_MIN_SPEND_NOT_MET: "PROMOTION_MIN_SPEND_NOT_MET",

  // Payment
  PAYMENT_DECLINED: "PAYMENT_DECLINED",
  PAYMENT_NOT_READY: "PAYMENT_NOT_READY",
  PAYMENT_METHOD_UNAVAILABLE: "PAYMENT_METHOD_UNAVAILABLE",
  PAYMENT_METHOD_NOT_COD: "PAYMENT_METHOD_NOT_COD",

  // Orders
  ORDER_NOT_CANCELLABLE: "ORDER_NOT_CANCELLABLE",
  NO_REORDERABLE_ITEMS: "NO_REORDERABLE_ITEMS",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",

  // Shipping
  SHIPPING_UNAVAILABLE: "SHIPPING_UNAVAILABLE",

  // Rate limiting
  RATE_LIMITED: "RATE_LIMITED",

  // Account
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  RESET_TOKEN_INVALID: "RESET_TOKEN_INVALID",
  RESET_TOKEN_EXPIRED: "RESET_TOKEN_EXPIRED",

  // System
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/**
 * HTTP status codes mapping
 */
export const ErrorHttpStatus: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  AUTH_INVALID_CREDENTIALS: 401,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  ENTITY_NOT_FOUND: 404,
  PRODUCT_NOT_FOUND: 404,
  VARIANT_NOT_FOUND: 404,
  ORDER_NOT_FOUND: 404,
  ADDRESS_NOT_FOUND: 404,
  DUPLICATE_EMAIL: 409,
  DUPLICATE_SKU: 409,
  DUPLICATE_SLUG: 409,
  DUPLICATE_PROMOTION_CODE: 409,
  DUPLICATE_RESOURCE: 409,
  DUPLICATE_REQUEST: 409,
  OUT_OF_STOCK: 409,
  INVALID_STOCK_ADJUSTMENT: 409,
  CART_EMPTY: 409,
  CHECKOUT_EXPIRED: 409,
  CHECKOUT_NOT_ALLOWED: 409,
  PROMOTION_INVALID: 409,
  PROMOTION_EXPIRED: 409,
  PROMOTION_LIMIT_REACHED: 409,
  PROMOTION_MIN_SPEND_NOT_MET: 409,
  PAYMENT_DECLINED: 402,
  PAYMENT_NOT_READY: 409,
  PAYMENT_METHOD_UNAVAILABLE: 409,
  PAYMENT_METHOD_NOT_COD: 409,
  ORDER_NOT_CANCELLABLE: 409,
  NO_REORDERABLE_ITEMS: 409,
  INVALID_STATE_TRANSITION: 409,
  SHIPPING_UNAVAILABLE: 409,
  RATE_LIMITED: 429,
  ACCOUNT_DISABLED: 403,
  ACCOUNT_LOCKED: 403,
  RESET_TOKEN_INVALID: 400,
  RESET_TOKEN_EXPIRED: 400,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};
